---
- name: "[{{ item.iface | upper }}] Enable"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/enable"
    state: present

- name: "[{{ item.iface | upper }}] Set Range Start"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/range/from"
    value: "{{ item.range.start }}"

- name: "[{{ item.iface | upper }}] Set Range End"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/range/to"
    value: "{{ item.range.end }}"

- name: "[{{ item.iface | upper }}] Set DNS server"
  community.general.xml:
    pretty_print: true
    path: "{{ local_file }}"
    xpath: "{{ xpath }}/dnsserver"
    value: "{{ item.dns }}"
